# Generated by Django 5.0.6 on 2024-07-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('instruction', models.TextField(max_length=400)),
                ('imageAdress', models.CharField(max_length=200)),
            ],
        ),
    ]
