# Generated by Django 5.0.6 on 2024-07-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('pricePerMonth', models.PositiveIntegerField()),
                ('numberOfUsers', models.PositiveIntegerField()),
                ('storageInGB', models.PositiveIntegerField()),
                ('support', models.CharField(max_length=100)),
                ('helpCenterAccess', models.BooleanField()),
            ],
        ),
    ]
