# Generated by Django 5.0.6 on 2024-07-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
    ]
