# Generated by Django 5.0.6 on 2024-07-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emailId', models.EmailField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('totalProject', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('rollNumber', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
